"""add content_approved to checkins

Revision ID: f4ce3438c218
Revises: 85699383f95a
Create Date: 2026-04-03 13:32:31.072386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f4ce3438c218'
down_revision: Union[str, Sequence[str], None] = '85699383f95a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('checkins', sa.Column('content_approved', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('checkins', 'content_approved')
    # ### end Alembic commands ###
